### ISSUE TITLE
不开源么？

### ISSUE THREAD

**Issue by goplayegg** [succlz123/AcFun-Client-Multiplatform#1]
我的AcfunQml遇到点问题，登录后 比如获取用户信息 发弹幕 等接口服务器都报未认证。安卓客户端抓包看cookie里有个 token怎么得到，跟登录返回的里面几个token都不一样

**Comment by CrystalSpire** [comment]
我的数据是通过 xpath 解析 网页端 html 数据来的, 因为现在 acfun 接口都有 token 验证,很麻烦.

**Comment by CrystalSpire** [comment]
所以目前没有登录功能,  等有空再研究下, 如何通过 网页获取用户登录 cookie 之类, 开源等什么时候折腾完了再说.

**Comment by goplayegg** [comment]
解决了 Cookie里acPasstoken的t必须是小写的 尽管登陆返回的是大写T
