### ISSUE TITLE
加油啊铁子

### ISSUE THREAD

**Issue by zengyunsi** [succlz123/AcFun-Client-Multiplatform#12]
万众期待！

**Comment by zengyunsi** [comment]
关于tv版本 热度蛮高的  希望支持弹幕 能够搜索 查看up主主页 有红包赞助

**Comment by CrystalSpire** [comment]
没官方接口做起来很累的, 搜索之类功能下次一定

**Comment by succlz123** [comment]
@zengyunsi 可以看看现在的 release https://github.com/succlz123/AcFun-Client-Multiplatform/releases/
