### ISSUE TITLE
感谢大神更新，提交一点问题

### ISSUE THREAD

**Issue by zengyunsi** [succlz123/AcFun-Client-Multiplatform#14]
1.小米电视打开会显示正在使用移动网络，我感觉这个提示没啥用，可以去掉
2.看完一个片，按返回会收到首页，不是之前在的栏目，比如在娱乐区看了一个视频，返回以后又回到了推荐。
3.看片的时候，没办法调音量，要返回调再看
4.没办法回到之前的进度
5.弹幕好像有点问题，是不是快进以后就没了···

**Comment by CrystalSpire** [comment]
好的, 最近有点忙没怎么看, 我有空看下

**Comment by succlz123** [comment]
可以看看现在的 release https://github.com/succlz123/AcFun-Client-Multiplatform/releases/
