### ISSUE TITLE
少见的A站TV端，请问大佬不再更新了吗？

### ISSUE THREAD

**Issue by drw2005** [succlz123/AcFun-Client-Multiplatform#18]
大佬是时侯在百忙之中推出新版本了啊：）

**Comment by succlz123** [comment]
换了个新东西，先搞完桌面和手机端再适配 TV

**Comment by drw2005** [comment]
> 换了个新东西，先搞完桌面和手机端再适配 TV

谢谢大佬回复，其实TV版受众也很多，尤其类似AB站这类的。
A站TV端少之又少，大佬考虑下优先级。
