### ISSUE TITLE
安卓13无法播放视频

### ISSUE THREAD

**Issue by fqscfqj** [succlz123/AcFun-Client-Multiplatform#19]
![032b3c7dcb89ffd941bf85f66823acb](https://user-images.githubusercontent.com/68098251/194677462-3daa03ed-0bab-4fbe-b171-a386d6375bb9.jpg)
realme gt2

**Comment by succlz123** [comment]
好的，应该是没适配好手机的布局，详情页下次会改掉。你也可以打开屏幕自动旋转，切到横屏应该就正常了。

**Comment by succlz123** [comment]
看下最新的 1.0.4，试试

**Comment by fqscfqj** [comment]
> 看下最新的 1.0.4，试试

可以播放了，还有俩问题
1.手机这边播放视频的时候不会强制横屏播放
2.windows端播放选集的时候控件可点范围太小，必须点在数字上才会进入视频
![image](https://user-images.githubusercontent.com/68098251/195124340-ea4b3543-f816-4ec1-953c-103e582b3941.png)

**Comment by succlz123** [comment]
了解了，下次改下
