### ISSUE TITLE
有线连接提示“正在使用移动网络”

### ISSUE THREAD

**Issue by featherwit** [succlz123/AcFun-Client-Multiplatform#2]
设备为一台Nvidia Shield TV (2019)。
网络为有线连接。
播放时会提示“正在使用移动网络”而无法继续播放。

**Comment by CrystalSpire** [comment]
嗯, 我改下.

**Comment by CrystalSpire** [comment]
@featherwit 更新了, 用 1.1 试试.

**Comment by featherwit** [comment]
> 
> 
> @featherwit 更新了, 用 1.1 试试.

问题已解决，感谢修复~
