### ISSUE TITLE
麻烦编译个32位的版本，Sony电视安装失败

### ISSUE THREAD

**Issue by BlackJackonGH** [succlz123/AcFun-Client-Multiplatform#20]
希望大佬能编译个32位的版本，Sony电视安装失败。

**Comment by succlz123** [comment]
https://github.com/succlz123/AcFun-Client-Multiplatform/releases/tag/v1.0.5
@xzp44 可以试试最新版本

**Comment by BlackJackonGH** [comment]
1.0.5安装成功，可以使用。
在播放界面遥控器无法选中设置按钮，不过问题不大。
感谢大佬。

**Comment by succlz123** [comment]
之后有空会再优化下的，包括首页搜索。
