### ISSUE TITLE
在稿件方块上按菜单键可能卡住

### ISSUE THREAD

**Issue by Sokwva** [succlz123/AcFun-Client-Multiplatform#3]
在分区下的投稿方块儿上，按菜单键（本来想试试看有没有比如收藏之类的功能），发现界面卡住，上下左右均无响应

**Comment by CrystalSpire** [comment]
嗯, 有空看下

**Comment by CrystalSpire** [comment]
是首页吗, 奇怪我这边没有对菜单键做特殊处理哦.

**Comment by Sokwva** [comment]
> 是首页吗, 奇怪我这边没有对菜单键做特殊处理哦.

莫非与系统有关，我是在分区的子板块下面测试的，可能是系统识别进行了操作。如果你那边测试没有问题的话我还是把这个issue关了。
其实我建议加上右键菜单，来个稍后再看的列表之类的_(•̀ω•́ 」∠)_
