### ISSUE TITLE
查看用户投稿

### ISSUE THREAD

**Issue by Sokwva** [succlz123/AcFun-Client-Multiplatform#4]
希望能查看用户的投稿，比如我在稿件页面中可以跳转至用户投稿界面，查看此Up的投稿。

现有可用的接口：https://api-new.app.acfun.cn/rest/app/user/resource/query?count=20&authorId=23682490&resourceType=2&sortType=3&status=1&pcursor=0

（返回20个稿件，类型是视频）

**Comment by CrystalSpire** [comment]
哈哈, 可以有空加下.

**Comment by CrystalSpire** [comment]
搞定, 看看有什么问题不

**Comment by Sokwva** [comment]
> 搞定, 看看有什么问题不

覆盖安装之后，进入app直接闪退；再也进不去了，重装都不行。

**Comment by CrystalSpire** [comment]
尴尬 我看下可能是 release 打的包的问题吧

**Comment by CrystalSpire** [comment]
fixed
