### ISSUE TITLE
要不要加下弹幕功能呀~

### ISSUE THREAD

**Issue by onewesong** [succlz123/AcFun-Client-Multiplatform#7]

**Comment by okayark** [comment]
的确，个人觉得弹幕功能可能是首要的，其它的不足可以忍受。
一般播放的话A站自带的投屏效果已经不错了，但是没弹幕。

**Comment by Sokwva** [comment]
现有的弹幕接口=> [POST videoId=13924311&lastFetchTime=] https://www.acfun.cn/rest/pc-direct/new-danmaku/poll
需要提供cookies

**Comment by CrystalSpire** [comment]
hh 再说

**Comment by zengyunsi** [comment]
肯定要啊 不然还不如看投屏

**Comment by CrystalSpire** [comment]
有了, 看最新的 1.12, 但是不支持高级弹幕
